#!/usr/bin/env bash
#
# Adjust default output device volume
#
# Requires libpulse (pactl)
#
# Author:  Jesse Mirabel <sejjymvm@gmail.com>
# Date:    September 07, 2025
# License: MIT

DEF_VALUE=1
MIN=0
MAX=100

usage() {
	local script=${0##*/}

	cat <<- EOF
		USAGE: $script output {mute|raise|lower} [value]

		Adjust default output device volume

		OPTIONS:
		  mute             Toggle device mute
		  raise [value]    Raise volume by [value] (default: $DEF_VALUE)
		  lower [value]    Lower volume by [value] (default: $DEF_VALUE)

		EXAMPLES:
		  Raise speaker volume:
		    $ $script output raise

		  Lower speaker volume by 5:
		    $ $script output lower 5
	EOF
}

pactl() {
	command pactl "$1" "@DEFAULT_SINK@" "${@:2}"
}

get_volume() {
	pactl "get-sink-volume" | awk '{print $5}' | tr -d '%'
}

set_state() {
	pactl "set-sink-mute" toggle
}

set_volume() {
	local level
	level=$(get_volume)

	local new_level

	case $ACTION in
		raise)
			new_level=$((level + VALUE))
			if ((new_level > MAX)); then
				new_level=$MAX
			fi
			;;
		lower)
			new_level=$((level - VALUE))
			if ((new_level < MIN)); then
				new_level=$MIN
			fi
			;;
	esac

	pactl "set-sink-volume" "$new_level%"
}

main() {
	DEVICE=$1
	ACTION=$2
	VALUE=${3:-$DEF_VALUE}

	if [[ $DEVICE != "output" ]]; then
		usage >&2
		return 1
	fi

	if ((VALUE < 1)); then
		usage >&2
		return 1
	fi

	case $ACTION in
		mute)
			set_state
			;;
		raise | lower)
			set_volume
			;;
		*)
			usage >&2
			return 1
			;;
	esac
}

main "$@"
