#!/bin/bash

BLANK='#000000'
CLEAR='#000000'
DEFAULT='#ad5a1a'
TEXT='#ffffff'
INPUT='#1DB954'
VERIFYING='#F0C550'
WRONG='#E00000'

i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--layout-color=$TEXT         \
--keyhl-color=$INPUT         \
--bshl-color=$WRONG          \
--radius 120                 \
--ring-width 8               \
--blur 5                     \
--clock                      \
--indicator                  \
--time-size 40               \
--time-color=$TEXT           \
--time-str="%H:%M"           \
--time-pos="ix:(iy-20)"      \
--date-size 18               \
--date-color=$TEXT           \
--date-str="%A, %d.%m.%Y"    \
--keylayout 1                \
