# TODO: this config file is not compatible with the latest (v0.30) version

# TODO
# icons_format = "{icon}"

[theme]
theme = "gruvbox-dark"

[icons]
icons = "material-nf"

# [[block]]
# block = "focused_window"
# [block.format]
# full = " $title.str(max_w:15) |"
# short = " $title.str(max_w:10) |"

[[block]]
block = "music"
format = " $icon  {$combo.str(max_w:24,rot_interval:0.5) $prev $play $next |}"
interface_name_exclude = [".*kdeconnect.*", "mpd"]
[[block.click]]
button = "up"
action = "volume_up"
[[block.click]]
button = "down"
action = "volume_down"
[block.theme_overrides]
info_bg = "#1DB954"
info_fg = "#000000"

# TODO: add icon or something
[[block]]
block = "hueshift"
hue_shifter = "redshift"
step = 100
click_temp = 3500
[block.theme_overrides]
idle_bg = "#610008"

[[block]]
block = "backlight"
device = "intel_backlight"
[block.theme_overrides]
idle_bg = "#610008"

[[block]]
block = "custom"
command = ''' echo \  `xkblayout-state print %n` '''
signal = 0
# TODO
# [[block.click]]
# button = "left"
# cmd = ""
[block.theme_overrides]
idle_bg = "#ad5a1a"
idle_fg = "#ffffff"

[[block]]
block = "sound"
[block.theme_overrides]
idle_bg = "#1DB954"
idle_fg = "#000000"

[[block]]
block = "cpu"
interval = 2
format = "  $icon $utilization "
[block.theme_overrides]
idle_bg = "#458588"
idle_fg = "#000000"

[[block]]
block = "memory"
interval = 5
warning_mem = 70
warning_swap = 70
critical_mem = 90
critical_swap = 90
format = "$icon $mem_used_percents.eng(w:1) "
[block.theme_overrides]
idle_bg = "#458588"
idle_fg = "#000000"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid ~$frequency | Wired connection}"
[[block.click]]
button = "left"
cmd = "alacritty -e nmtui"
[block.theme_overrides]
good_bg = "#282828"

[[block]]
block = "battery"
interval = 60
format = "  $icon $percentage ($time)"
[block.theme_overrides]
good_bg = "#262a75"
info_bg = "#262a75"
warning_bg = "#262a75"

[[block]]
block = "time"
interval = 60
[block.format]
full = "  $icon $timestamp.datetime(f:%R) "
